services:
  # Infra
  db:
    image: mongodb/mongodb-community-server:6.0.15-ubuntu2204
    command: ["--replSet", "rs0", "--bind_ip_all", "--port", "27017"]
    restart: always
    ports:
      - "27018:27017"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    healthcheck:
      test: echo "try { rs.status() } catch (err) { rs.initiate({_id:'rs0',members:[{_id:0,host:'host.docker.internal:27018'}]}) }" | mongosh --port 27017 --quiet
      interval: 5s
      timeout: 30s
      start_period: 0s
      start_interval: 1s
      retries: 30

